# Generated by Django 5.2.17 on 2026-09-23 19:16

import benches.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Lets the GiST exclusion constraint compare bench_id with =.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Bench",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plaque_code",
                    models.CharField(
                        help_text="Human-readable ID, e.g. VC-214.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("area", models.CharField(db_index=True, max_length=80)),
                ("location_description", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_repair", "Under repair"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "benches",
                "ordering": ["plaque_code"],
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("public_display_name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        help_text="Exclusive: the term covers [start_date, end_date)."
                    ),
                ),
                ("dedication_text", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bench",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoptions",
                        to="benches.bench",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoptions",
                        to="benches.donor",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="adoption_end_after_start",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status", "active")),
                        expressions=[
                            ("bench", "="),
                            (benches.models.DateRange("start_date", "end_date"), "&&"),
                        ],
                        name="no_overlapping_adoptions",
                        violation_error_message="This bench is already adopted for part of that term.",
                    ),
                ],
            },
        ),
    ]
